### ISSUE TITLE
"prefix" not found

### ISSUE THREAD

**Issue by xadressesMan** [MAGGIx1404/Textify.js#24]
when we are try to use,

```
import Textify from "textify.js;

const alternatesAnimations = new Textify({
    selector: ".dynamic_text"
});

```

console make error like : 

```
ERROR in ./node_modules/textify.js/src/components/Animation.js 1:0-28
Module not found: Error: can't resolve 'prefix' in "D:\works.............................
```"

update, devDependecies or reCheck src's all js file

**Comment by MAGGIx1404** [comment]
thanks for the inform bug, we start working on it...

**Comment by Nikkiaramana** [comment]
`prefix not found 
`
or

`can't resolve prefix`

both error come in next.js

**Comment by MAGGIx1404** [comment]
> `prefix not found ` or
> 
> `can't resolve prefix`
> 
> both error come in next.js

working on this !!!!

**Comment by henaDenial** [comment]
> `prefix not found ` or
> 
> `can't resolve prefix`
> 
> both error come in next.js

download prefix dependency in your project and restart your web-servers. may that works

**Comment by daniealAroja** [comment]
> > `prefix not found ` or
> > `can't resolve prefix`
> > both error come in next.js
> 
> download prefix dependency in your project and restart your web-servers. may that works

it's work, but all time we can't use it like this way. 
that error make big trouble for next.js project

**Comment by MAGGIx1404** [comment]
error was fixed... :100:
