### ISSUE TITLE
Nuxt or Vue compiler errors

### ISSUE THREAD

**Issue by maniserVilla** [MAGGIx1404/Textify.js#25]
Nuxt and Vue compiler make error,

```
ERROR in ./node_modules/textify.js/src/components/Animation.js 1:0-89
Module not found: Error: can't resolve 'prefix' in "D:\travel-app\src\animations\text.js......
```

this error make lot of problem in my app. fix it please..

**Comment by maniserVilla** [comment]
letest version of vue and nuxt are in used.

**Comment by MAGGIx1404** [comment]
we are working on it!!!

**Comment by Nikkiaramana** [comment]
same error come with next.js !!!

**Comment by Priyanshu2055** [comment]
we are fixing very soon all error or bug .

**Comment by henaDenial** [comment]
> Nuxt and Vue compiler make error,
> 
> ```
> ERROR in ./node_modules/textify.js/src/components/Animation.js 1:0-89
> Module not found: Error: can't resolve 'prefix' in "D:\travel-app\src\animations\text.js......
> ```
> 
> this error make lot of problem in my app. fix it please..

download prefix in dependency and restart next js or nuxt server with deleting server_caches

**Comment by MAGGIx1404** [comment]
> > Nuxt and Vue compiler make error,
> > ```
> > ERROR in ./node_modules/textify.js/src/components/Animation.js 1:0-89
> > Module not found: Error: can't resolve 'prefix' in "D:\travel-app\src\animations\text.js......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this error make lot of problem in my app. fix it please..
> 
> download prefix in dependency and restart next js or nuxt server with deleting server_caches

error was fixed.. :100:
