### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by julianlaibach** [MAGGIx1404/Textify.js#34]
Hey @MAGGIx1404 thank you for this Package!

is there any reason why you console.log this.transformPrefix? Its located in /src/Animations/Text.js.

And could you maybe remove it?

Best,
Julian

**Comment by MAGGIx1404** [comment]
Hey bro, thanks for your review. We will remove this things in new version and that new we also add new animations of text also. And it is release in 1 ya 2 weeks. Thanks for support

**Comment by MAGGIx1404** [comment]
We will fix it in few week

**Comment by julianlaibach** [comment]
Hey @MAGGIx1404 is there any update on this? Thank you in advance!!

**Comment by holyboly** [comment]
`/src/Animations/Text.js:49`

`console.log(this.transformPrefix);`

Could you please remove this line? My console is already sweating.

**Comment by MAGGIx1404** [comment]
@holyboly and @julianlaibach, we fixed this issue in the new version of v2.2.2. thanks for support
